# Dockerfile
FROM python:3.9-slim

WORKDIR /event_management

COPY requirements.txt /event_management/
RUN pip install -r requirements.txt

COPY . /event_management/

EXPOSE 8000

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
